# Generated by Django 3.2.9 on 2022-02-23 11:30

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zipper_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type4', models.CharField(blank=True, default='Zipper_Product', max_length=50, null=True)),
                ('Z_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('Country_4', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('Size_Zipper', models.CharField(blank=True, max_length=25, null=True)),
                ('Z_Price', models.IntegerField(blank=True, null=True)),
                ('Z_Color_Picker', models.CharField(blank=True, max_length=50, null=True)),
                ('Roller', models.CharField(blank=True, max_length=25, null=True)),
                ('Z_Upload_Image', models.ImageField(blank=True, null=True, upload_to='Service_data')),
                ('D_Description', models.TextField(blank=True, null=True)),
                ('Zipper_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'zipper',
                'db_table': 'zipperCategory',
            },
        ),
        migrations.CreateModel(
            name='Thread_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type2', models.CharField(blank=True, default='Thread_Product', max_length=50, null=True)),
                ('Thread_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('Thread_Price', models.CharField(blank=True, max_length=50, null=True)),
                ('Thread_Available_Quantity', models.CharField(blank=True, max_length=25, null=True)),
                ('Thread_Description', models.TextField(blank=True, null=True)),
                ('Thread_Image', models.ImageField(blank=True, null=True, upload_to='Post_Product')),
                ('Thread_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'thread',
                'db_table': 'ThreadCategory',
            },
        ),
        migrations.CreateModel(
            name='PostService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supplier_Name', models.CharField(blank=True, max_length=25, null=True)),
                ('Business_Country_Location', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('Tailor_Specialization', models.CharField(blank=True, choices=[('CASUAL CLOTHES', 'CASUAL CLOTHES'), ('WEDDING SERVICES', 'WEDDING SERVICES'), ('SUIT RESIZING', 'SUIT RESIZING'), ('DESHDASHA', 'DESHDASHA'), ('GOWN DRESSES', 'GOWN DRESSES'), ('CUSTOM ACCESSORIES', 'CUSTOM ACCESSORIES')], max_length=50, null=True)),
                ('Experience', models.CharField(blank=True, max_length=50, null=True)),
                ('Multinational_Shippping', models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=25, null=True)),
                ('Targeted_Customer', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Casual Clothes', max_length=25, null=True)),
                ('Tailor_Staff_Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=25, null=True)),
                ('Phone_Number', models.IntegerField(blank=True, null=True)),
                ('Full_Address', models.TextField(blank=True, null=True)),
                ('Check_Box', models.BooleanField()),
                ('service_disc', models.TextField(blank=True, null=True)),
                ('service_image', models.ImageField(blank=True, upload_to='Service_data')),
                ('Service_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Febric_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type1', models.CharField(blank=True, default='Febric_Product', max_length=50, null=True)),
                ('Country_Origin', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('Fabric_Type', models.CharField(blank=True, max_length=50, null=True)),
                ('Tailor_Specialization', models.CharField(blank=True, max_length=25, null=True)),
                ('Fabric_Price', models.CharField(blank=True, max_length=25, null=True)),
                ('Fabric_Available_Quantity', models.CharField(blank=True, max_length=25, null=True)),
                ('Fabric_Season', models.CharField(blank=True, max_length=25, null=True)),
                ('Other_Description', models.TextField(blank=True, null=True)),
                ('Upload_Image', models.ImageField(blank=True, null=True, upload_to='Post_Product')),
                ('Size_Width', models.IntegerField(blank=True, null=True)),
                ('Check_Febric', models.BooleanField(blank=True, null=True)),
                ('Febric_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'febric',
                'db_table': 'ProductCategory',
            },
        ),
        migrations.CreateModel(
            name='Bottun_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type3', models.CharField(blank=True, default='Bottun_Product', max_length=50, null=True)),
                ('Type_Of_Material', models.CharField(blank=True, max_length=50, null=True)),
                ('Origin', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('Size', models.IntegerField(blank=True, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Color_Picker', colorfield.fields.ColorField(default='#FFFFFFFF', image_field=None, max_length=18, samples=None)),
                ('B_Description', models.TextField(blank=True, null=True)),
                ('B_Upload_Image', models.ImageField(blank=True, null=True, upload_to='Service_data')),
                ('B_Upload_Image_1', models.ImageField(blank=True, null=True, upload_to='Service_data')),
                ('Bottun_User', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'bottum',
                'db_table': 'bottumCategory',
            },
        ),
    ]
