# Generated by Django 3.2.9 on 2022-02-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='How_Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(blank=True, max_length=50, null=True)),
                ('Title_work', models.CharField(blank=True, max_length=50, null=True)),
                ('discription_work', models.TextField(blank=True, null=True)),
                ('image_work', models.ImageField(blank=True, null=True, upload_to='Home_work')),
                ('image_work_line', models.ImageField(blank=True, null=True, upload_to='Home_work')),
            ],
            options={
                'verbose_name_plural': 'How_IT_Work',
                'db_table': 'Howitwork',
            },
        ),
    ]
