# Generated by Django 3.2.7 on 2022-03-11 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='findproduct_background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findproductlogo', models.ImageField(blank=True, null=True, upload_to='product_logo')),
            ],
        ),
        migrations.CreateModel(
            name='findservice_background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findservicelogo', models.ImageField(blank=True, null=True, upload_to='service_logo')),
            ],
        ),
        migrations.CreateModel(
            name='findSupplier_background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findSupplierlogo', models.ImageField(blank=True, null=True, upload_to='supplier_logo')),
            ],
        ),
        migrations.CreateModel(
            name='home_background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homelogo', models.ImageField(blank=True, null=True, upload_to='home_logo')),
            ],
        ),
        migrations.CreateModel(
            name='ragister_background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ragisterlogo', models.ImageField(blank=True, null=True, upload_to='ragister_logo')),
            ],
        ),
    ]
