# Generated by Django 3.2.7 on 2022-03-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_findproduct_background_findservice_background_findsupplier_background_home_background_ragister_backg'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragister_background',
            name='aboutlogo',
            field=models.ImageField(blank=True, null=True, upload_to='about_logo'),
        ),
        migrations.AddField(
            model_name='ragister_background',
            name='contactlogo',
            field=models.ImageField(blank=True, null=True, upload_to='contact_logo'),
        ),
    ]
