# Generated by Django 3.2.9 on 2022-02-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(blank=True, max_length=25, null=True)),
                ('sub_tittle', models.TextField(blank=True, null=True)),
                ('about_disc', models.TextField(blank=True, null=True)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='About_data')),
            ],
        ),
    ]
