# Generated by Django 3.2.9 on 2022-02-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(blank=True, max_length=25, null=True)),
                ('discription', models.TextField(blank=True, null=True)),
                ('questions', models.CharField(blank=True, max_length=250, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('faq_image', models.ImageField(blank=True, null=True, upload_to='Faq_data')),
            ],
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle_privacy', models.CharField(blank=True, max_length=25, null=True)),
                ('discription_privacy', models.TextField(blank=True, null=True)),
                ('privacy_image', models.ImageField(blank=True, null=True, upload_to='Privacy_data')),
            ],
        ),
    ]
